name: TMView Watch

on:
  workflow_dispatch:

  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium

      - name: Run watch
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python watch.py

